name: Deploy to PyPi

on:
  push:
    branches:
      - main

permissions:
  contents: write

concurrency: "main"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version:
          - 3.8
          - 3.9
          - 3.10

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build bump2version
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdit --wheel --outdir dist/
      # Wait until successful build to configure git and bump versions
      - name: Configure Git
        run: |
          git config user.name "Bump Version"
          git config user.email "bump-version@users.noreply.github.com"
      - name: Bump Major Version
        run: |
          bump2version major
          echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
        if: "startsWith(github.event.head_commit.message, '[MAJOR]')"
      - name: Bump Minor Version
        run: |
          bump2version minor
          echo "SKIPBUMP=TRUE" >> $GITHUB_ENV
        if: "startsWith(github.event.head_commit.message, '[FEATURE]')"
      # Default action
      - name: Bump Patch Version
        run: |
          bump2version patch
        if: env.SKIPBUMP == 'FALSE'

      - name: Push commit
        run: git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git --follow-tags

      - name: Deploy to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}